#!/bin/sh

CONFIG_FILES="$HOME/.config/waybar/config $HOME/.config/waybar/style.css"

declare -A NEEDED_BINS=(
  'inotifywait',
  'waybar'
)

die() {
  echo $@ >&2
  exit 1
}

for bin in $NEEDED_BINS; do
  [[ ! -z `command -v $bin` ]] || die "Missing required PATH executable: $bin"
done

for conf in $CONFIG_FILES; do
   [[  -f "$conf" ]] || die "Missing config file: $conf"
done

trap "killall waybar" EXIT

while true; do
    waybar &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
